apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: delivery-pipeline-deployer-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: service-deployer-dev
   profiles: [dev]
 - targetId: service-deployer-prod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: service-deployer-dev
description: Cloud Run development service
run:
 location: projects/jdecode/locations/asia-southeast1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: service-deployer-prod
description: Cloud Run production service
run:
  location: projects/jdecode/locations/asia-southeast1
